# Generated by Django 2.0.7 on 2018-07-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Valore')),
            ],
        ),
        migrations.CreateModel(
            name='seme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Valore')),
                ('colore', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='carta',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carta', to='setteMezzo.seme'),
        ),
    ]
